name: Lint and Fix Python Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      # Lint files with flake8
      - name: Run flake8
        run: flake8 .

      # Auto-format with Black
      - name: Auto-format with Black
        run: black . --check || black .

      # Commit and push fixes if needed
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-fixed linting issues" || echo "No changes to commit"
          git push || echo "No changes to push"
